INSERT INTO TODO(ID, NAME, DESCRIPTION, TARGET_DAY, DONE)
VALUES(1001, 'axel', 'Get AWS Certified', CURRENT_DATE(), false);

INSERT INTO TODO(ID, NAME, DESCRIPTION, TARGET_DAY, DONE)
VALUES(1002, 'axel', 'Get Azure Certified', CURRENT_DATE(), false);

INSERT INTO TODO(ID, NAME, DESCRIPTION, TARGET_DAY, DONE)
VALUES(1003, 'axel', 'Get GPC Certified', CURRENT_DATE(), false);

INSERT INTO TODO(ID, NAME, DESCRIPTION, TARGET_DAY, DONE)
VALUES(1004, 'axel', 'Learn Full Stack', CURRENT_DATE(), false);
